services:
  - type: web
    name: symfony-api
    runtime: docker
    rootDir: api
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        fromDatabase:
          name: taskly-postgres
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

  - type: web
    name: next-client
    env: node
    rootDir: client
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://symfony-api.onrender.com
    autoDeploy: true

databases:
  - name: taskly-postgres
    plan: free


